[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ricalanis/openenv-hackaton/blob/main/training/train_answering.ipynb)

# DataSage Stage 3: Answering GRPO Training

Pre-builds dataset with real environment observations (no `rollout_func`).
Reward functions replay the env with stored seeds for context-matched evaluation.
Includes Patronus Lynx integration for hallucination detection (optional).

**Fully self-contained** — runs in Colab with no repo clone or project imports.

**Requirements:** GPU (A100/H100), `HF_TOKEN`, `WANDB_API_KEY`.  
**Optional:** `PATRONUS_API_KEY` for Patronus Lynx.

In [1]:
# Setup: install dependencies
!pip install -q unsloth vllm trl datasets wandb requests
!pip install -q patronus  # optional

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.3/70.3 kB 4.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 6.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.9/87.9 kB 9.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 447.0/447.0 kB 25.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 432.9/432.9 MB 5.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 192.6/192.6 kB 28.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 7.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 158.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.0/111.0 kB 17.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.4/45.4 kB 6.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 184.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 165.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.9/34.9 MB 88.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.1/423.1 kB 59.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 506.8/506.8 kB 68.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 455.2/455.2 kB 62.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 44.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.2/114.2 kB 16.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 322.0/322.0 kB 51.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 169.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 204.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.7/105.7 kB 17.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.3/74.3 MB 36.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 176.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.1/72.1 kB 11.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.0/142.0 kB 25.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.7/68.7 kB 11.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 231.6/231.6 kB 38.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 MB 61.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 165.3/165.3 kB 27.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.0/73.0 MB 36.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 118.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 189.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 74.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 393.8/393.8 kB 62.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 165.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 388.0/388.0 kB 61.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 285.4/285.4 kB 49.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 323.5/323.5 kB 53.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 170.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.7/149.7 kB 23.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.9/224.9 kB 36.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 180.7/180.7 kB 31.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.6/71.6 kB 11.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 181.9/181.9 kB 30.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 173.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.4/42.4 MB 68.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 160.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.3/74.3 kB 12.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 320.7/320.7 kB 49.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 176.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 8.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 897.8/897.8 kB 111.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 51.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 198.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 821.6/821.6 kB 110.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 959.8/959.8 kB 120.5 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
google-adk 1.26.0 requires opentelemetry-api<1.39.0,>=1.36.0, but you have opentelemetry-api 1.40.0 which is incompatible.
google-adk 1.26.0 requires opentelemetry-sdk<1.39.0,>=1.36.0, but you have opentelemetry-sdk 1.40.0 which is incompatible.
google-ai-generativelanguage 0.6.15 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 6.33.5 which is incompatible.
opentelemetry-exporter-gcp-logging 1.11.0a0 requires opentelemetry-sdk<1.39.0,>=1.35.0, but you have opentelemetry-sdk 1.40.0 which is incompatible.
tensorflow 2.19.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3, but you have protobuf 6.33.5 which is incompatible.
grpcio-status 1.71.2 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 6.33.5 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.3/80.3 kB 4.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.3/131.3 kB 8.8 MB/s eta 0:00:00

In [2]:
# Load API keys from Colab Secrets or set manually
import os

try:
    from google.colab import userdata
    os.environ["HF_TOKEN"] = userdata.get("HF_TOKEN")
    os.environ["WANDB_API_KEY"] = userdata.get("WANDB_API_KEY")
    # Optional: for Patronus Lynx hallucination detection
    os.environ["PATRONUS_API_KEY"] = userdata.get("PATRONUS_API_KEY")
    print("Loaded keys from Colab Secrets")
except Exception:
    pass  # Fill manually below if not using Colab Secrets

# Uncomment and fill if not using Colab Secrets:
# os.environ["HF_TOKEN"] = "hf_..."
# os.environ["WANDB_API_KEY"] = "wandb_..."
# os.environ["PATRONUS_API_KEY"] = "pat_..."  # optional

assert os.environ.get("HF_TOKEN"), "Set HF_TOKEN in Colab Secrets or above"
print("Keys loaded.")

Loaded keys from Colab Secrets
Keys loaded.

In [3]:
# Config + parser + reward helpers (all inlined, no project imports)
import json
import re
import requests
from dataclasses import dataclass, field

# ---- Config constants ----
WANDB_PROJECT = "datasage"
BASE_MODEL = "unsloth/Qwen2.5-3B-Instruct"
ENV_URL = "https://ricalanis-datasage-answering.hf.space"
HF_REPO = "ricalanis/datasage-qwen-answering"

LEARNING_RATE = 3e-6
NUM_TRAIN_EPOCHS = 3
PER_DEVICE_TRAIN_BATCH_SIZE = 1
GRADIENT_ACCUMULATION_STEPS = 1
NUM_GENERATIONS = 8
MAX_COMPLETION_LENGTH = 256
MAX_PROMPT_LENGTH = 1024


# ---- Completion text extraction ----
def _get_text(completion) -> str:
    """Extract text from a completion (str or chat message list)."""
    if isinstance(completion, str):
        return completion
    if isinstance(completion, list):
        # Chat format: [{"role": "assistant", "content": "..."}]
        return completion[-1]["content"] if completion else ""
    return str(completion)


# ---- Parser ----
def parse_answering_action(text: str) -> dict:
    """Parse model output into an answering action dict."""
    json_match = re.search(r'\{[^{}]*"answer"[^{}]*\}', text, re.DOTALL)
    if json_match:
        try:
            data = json.loads(json_match.group())
            if "answer" in data:
                return data
        except json.JSONDecodeError:
            pass

    cited = re.findall(r'\b([A-Z][a-zA-Z]+(?:[A-Z][a-z]+)*)\b', text)
    return {
        "answer": text,
        "cited_columns": cited[:5],
        "reasoning": "",
    }


# ---- Persona definitions (inlined from environments/shared/personas.py) ----
@dataclass
class Persona:
    name: str
    role: str
    focus_areas: list[str]
    language_style: str
    keywords: list[str]
    anti_keywords: list[str]


PERSONAS = [
    Persona(
        name="Executive", role="executive",
        focus_areas=["costs", "ROI", "strategic risk", "portfolio trends", "year-over-year"],
        language_style="strategic-financial",
        keywords=["revenue", "cost", "ROI", "risk", "trend", "quarter",
                  "year-over-year", "impact", "budget", "margin", "growth"],
        anti_keywords=["I think", "maybe", "um", "idk"],
    ),
    Persona(
        name="Manager", role="manager",
        focus_areas=["team performance", "operational health", "process bottlenecks", "capacity"],
        language_style="operational-actionable",
        keywords=["team", "performance", "bottleneck", "capacity", "SLA",
                  "process", "action", "priority", "escalation", "delivery"],
        anti_keywords=["shareholder", "valuation", "IPO"],
    ),
    Persona(
        name="Individual Contributor", role="ic",
        focus_areas=["personal tasks", "deadlines", "what to do next", "simple explanations"],
        language_style="plain-personal",
        keywords=["my", "I should", "next step", "deadline", "help",
                  "understand", "priority", "task", "assigned"],
        anti_keywords=["KPI", "ROI", "portfolio", "strategic", "EBITDA"],
    ),
]


def _check_formality(text: str, style: str) -> float:
    """Check if text formality matches the expected language style."""
    text_lower = text.lower()
    if style == "strategic-financial":
        indicators = ["percent", "%", "million", "billion", "quarter", "fiscal",
                      "forecast", "benchmark", "metric"]
        hits = sum(1 for ind in indicators if ind in text_lower)
        return min(hits / 2.0, 1.0)
    elif style == "operational-actionable":
        indicators = ["action", "recommend", "should", "priority", "next steps",
                      "immediate", "plan", "schedule"]
        hits = sum(1 for ind in indicators if ind in text_lower)
        return min(hits / 2.0, 1.0)
    elif style == "plain-personal":
        sentences = text.split(".")
        avg_len = sum(len(s.split()) for s in sentences) / max(len(sentences), 1)
        return 1.0 if avg_len < 20 else max(0.0, 1.0 - (avg_len - 20) / 30)
    return 0.5


def score_persona_alignment(answer: str, persona: Persona) -> float:
    """Score how well an answer aligns with a persona's communication style."""
    answer_lower = answer.lower()
    words = re.findall(r'\w+', answer_lower)
    word_count = max(len(words), 1)

    keyword_hits = sum(1 for kw in persona.keywords if kw.lower() in answer_lower)
    keyword_score = min(keyword_hits / max(len(persona.keywords) * 0.3, 1), 1.0)

    anti_hits = sum(1 for akw in persona.anti_keywords if akw.lower() in answer_lower)
    anti_penalty = min(anti_hits * 0.15, 0.5)

    formality_score = _check_formality(answer, persona.language_style)

    raw_score = 0.50 * keyword_score + 0.20 * formality_score + 0.30 - anti_penalty
    return round(max(0.0, min(1.0, raw_score)), 4)


# ---- Reward helpers ----
_ANSWER_JSON_RE = re.compile(r'\{[^{}]*"answer"[^{}]*\}', re.DOTALL)


def persona_match_reward(completions, **kwargs) -> list[float]:
    """Reward alignment with the REQUESTED persona (not just any persona)."""
    persona_names = kwargs.get("persona_name", [])
    if not persona_names:
        return [0.0] * len(completions)
    persona_map = {p.name: p for p in PERSONAS}
    rewards = []
    for completion, p_name in zip(completions, persona_names):
        text = _get_text(completion)
        persona = persona_map.get(p_name)
        if persona:
            rewards.append(score_persona_alignment(text, persona))
        else:
            rewards.append(0.0)
    return rewards


def local_faithfulness_fn(completions, **kwargs) -> list[float]:
    """Local faithfulness heuristic: checks column citations and data grounding."""
    rewards = []
    for completion in completions:
        text = _get_text(completion)
        score = 0.0
        cited = re.findall(r'\b([A-Z][a-zA-Z]+(?:[A-Z][a-z]+)*)\b', text)
        if len(cited) >= 1:
            score += 0.3
        if len(cited) >= 3:
            score += 0.2
        if re.search(r'\d+\.?\d*%', text) or re.search(r'\b\d{2,}\b', text):
            score += 0.2
        if any(w in text.lower() for w in ["i believe", "probably", "might be",
                                            "i'm not sure", "i think maybe"]):
            score -= 0.2
        if len(text.strip()) < 50:
            score -= 0.3
        rewards.append(max(0.0, min(1.0, score)))
    return rewards


def patronus_reward_fn(completions, **kwargs) -> list[float]:
    """Use Patronus Lynx for hallucination detection, with local fallback."""
    api_key = os.environ.get("PATRONUS_API_KEY")
    if not api_key:
        return local_faithfulness_fn(completions, **kwargs)
    try:
        import patronus
        patronus.init()
        from patronus import Patronus, RemoteEvaluator
        client = Patronus()
        lynx = RemoteEvaluator("lynx", "patronus:hallucination")
        rewards = []
        for completion in completions:
            text = _get_text(completion)
            result = client.evaluate(
                evaluators=lynx,
                task_output=text,
                task_input="Answer the question based on the data.",
                task_context="",
            )
            rewards.append(float(result.results[0].score))
        return rewards
    except Exception:
        return local_faithfulness_fn(completions, **kwargs)


def answering_json_format_reward(completions, **kwargs) -> list[float]:
    """Reward well-formed JSON answer actions."""
    rewards = []
    for completion in completions:
        text = _get_text(completion)
        match = _ANSWER_JSON_RE.search(text)
        if match:
            try:
                data = json.loads(match.group())
                has_answer = bool(data.get("answer", "").strip())
                has_cited = bool(data.get("cited_columns"))
                has_reasoning = bool(data.get("reasoning", "").strip())
                if has_answer and has_cited and has_reasoning:
                    rewards.append(1.0)
                elif has_answer and has_cited:
                    rewards.append(0.7)
                elif has_answer:
                    rewards.append(0.4)
                else:
                    rewards.append(0.2)
            except (json.JSONDecodeError, AttributeError):
                rewards.append(0.2)
        else:
            rewards.append(0.0)
    return rewards


print(f"Environment URL: {ENV_URL}")
print(f"Base model: {BASE_MODEL}")

Environment URL: https://ricalanis-datasage-answering.hf.space
Base model: unsloth/Qwen2.5-3B-Instruct

In [4]:
# Model loading via Unsloth
from unsloth import FastLanguageModel

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=BASE_MODEL, max_seq_length=2048, load_in_4bit=True,
    fast_inference=True, max_lora_rank=16, gpu_memory_utilization=0.6,
)
model = FastLanguageModel.get_peft_model(
    model, r=16, lora_alpha=16, lora_dropout=0,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                    "gate_proj", "up_proj", "down_proj"],
    use_gradient_checkpointing="unsloth",
)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
print(f"Model loaded: {BASE_MODEL}")

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
INFO 03-08 10:21:20 [vllm_utils.py:723] Unsloth: Patching vLLM v1 graph capture
==((====))==  Unsloth 2026.3.3: Fast Qwen2 patching. Transformers: 4.57.6. vLLM: 0.17.0.
   \\   /|    NVIDIA RTX PRO 6000 Blackwell Server Edition. Num GPUs = 1. Max memory: 94.971 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 12.0. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth: vLLM loading unsloth/qwen2.5-3b-instruct-unsloth-bnb-4bit with actual GPU utilization = 59.54%
Unsloth: Your GPU has CUDA compute capability 12.0 with VRAM = 94.97 GB.
Unsloth: Using conservativeness = 1.0. Chunked prefill tokens = 2048. Num Sequences = 128.
Unsloth: vLLM's KV Cache can use up to 54.14 GB. Also swap space = 6 GB.
Unsloth: Not an error, but `use_cudagraph` is not supported in vLLM.config.CompilationConfig. Skipping.
Unsloth: Not an error, but `use_inductor` is not supported in vLLM.config.CompilationConfig. Skipping.
WARNING 03-08 10:21:27 [compilation.py:805] Level is deprecated and will be removed in the next release,either 0.12.0 or 0.11.2 whichever is soonest.Use mode instead.If both level and mode are given,only mode will be used.
Unsloth: Not an error, but `device` is not supported in vLLM. Skipping.
INFO 03-08 10:21:27 [utils.py:238] non-default args: {'load_format': 'bitsandbytes', 'dtype': torch.bfloat16, 'max_model_len': 2048, 'enable_prefix_caching': True, 'swap_space': 6, 'gpu_memory_utilization': 0.5953715968048864, 'max_num_batched_tokens': 8192, 'max_num_seqs': 128, 'max_logprobs': 0, 'disable_log_stats': True, 'quantization': 'bitsandbytes', 'enable_lora': True, 'enable_chunked_prefill': True, 'compilation_config': {'level': 3, 'mode': 3, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': [], 'splitting_ops': None, 'compile_mm_encoder': False, 'compile_sizes': None, 'compile_ranges_split_points': None, 'inductor_compile_config': {'epilogue_fusion': True, 'max_autotune': False, 'shape_padding': True, 'trace.enabled': False, 'triton.cudagraphs': False, 'debug': False, 'dce': True, 'memory_planning': True, 'coordinate_descent_tuning': False, 'trace.graph_diagram': False, 'compile_threads': 32, 'group_fusion': True, 'disable_progress': False, 'verbose_progress': True, 'triton.multi_kernel': 0, 'triton.use_block_ptr': True, 'triton.enable_persistent_tma_matmul': True, 'triton.autotune_at_compile_time': False, 'triton.cooperative_reductions': False, 'cuda.compile_opt_level': '-O2', 'cuda.enable_cuda_lto': True, 'combo_kernels': False, 'benchmark_combo_kernel': True, 'combo_kernel_foreach_dynamic_shapes': True, 'enable_auto_functionalized_v2': False}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': None, 'pass_config': {}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': None, 'static_all_moe_layers': []}, 'model': 'unsloth/qwen2.5-3b-instruct-unsloth-bnb-4bit'}
WARNING 03-08 10:21:27 [envs.py:1710] Unknown vLLM environment variable detected: VLLM_ATTENTION_BACKEND

/usr/local/lib/python3.12/dist-packages/pydantic/type_adapter.py:605: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `enum` - serialized value may not be as expected [field_name='mode', input_value=3, input_type=int])
  return self.serializer.to_python(

WARNING 03-08 10:21:28 [arg_utils.py:1321] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.
INFO 03-08 10:21:41 [model.py:531] Resolved architecture: Qwen2ForCausalLM
INFO 03-08 10:21:41 [model.py:1554] Using max model len 2048
INFO 03-08 10:21:41 [scheduler.py:231] Chunked prefill is enabled with max_num_batched_tokens=8192.
Unsloth: vLLM Bitsandbytes config using kwargs = {'load_in_8bit': False, 'load_in_4bit': True, 'bnb_4bit_compute_dtype': 'bfloat16', 'bnb_4bit_quant_storage': 'uint8', 'bnb_4bit_quant_type': 'nf4', 'bnb_4bit_use_double_quant': True, 'llm_int8_enable_fp32_cpu_offload': False, 'llm_int8_has_fp16_weight': False, 'llm_int8_skip_modules': ['lm_head', 'multi_modal_projector', 'merger', 'modality_projection', 'model.layers.2.mlp', 'model.layers.3.mlp', 'model.layers.30.mlp'], 'llm_int8_threshold': 6.0}
INFO 03-08 10:21:41 [vllm.py:747] Asynchronous scheduling is enabled.

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/605 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/271 [00:00<?, ?B/s]

INFO 03-08 10:21:45 [core.py:101] Initializing a V1 LLM engine (v0.17.0) with config: model='unsloth/qwen2.5-3b-instruct-unsloth-bnb-4bit', speculative_config=None, tokenizer='unsloth/qwen2.5-3b-instruct-unsloth-bnb-4bit', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=2048, download_dir=None, load_format=bitsandbytes, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=bitsandbytes, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=unsloth/qwen2.5-3b-instruct-unsloth-bnb-4bit, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': 3, 'mode': 3, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_split_points': [8192], 'inductor_compile_config': {'epilogue_fusion': True, 'max_autotune': False, 'shape_padding': True, 'trace.enabled': False, 'triton.cudagraphs': False, 'debug': False, 'dce': True, 'memory_planning': True, 'coordinate_descent_tuning': False, 'trace.graph_diagram': False, 'compile_threads': 32, 'group_fusion': True, 'disable_progress': False, 'verbose_progress': True, 'triton.multi_kernel': 0, 'triton.use_block_ptr': True, 'triton.enable_persistent_tma_matmul': True, 'triton.autotune_at_compile_time': False, 'triton.cooperative_reductions': False, 'cuda.compile_opt_level': '-O2', 'cuda.enable_cuda_lto': True, 'combo_kernels': False, 'benchmark_combo_kernel': True, 'combo_kernel_foreach_dynamic_shapes': True, 'enable_auto_functionalized_v2': False}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 256, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
INFO 03-08 10:21:45 [parallel_state.py:1393] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.28.0.12:43053 backend=nccl
INFO 03-08 10:21:45 [parallel_state.py:1715] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A

/usr/local/lib/python3.12/dist-packages/pydantic/type_adapter.py:605: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `enum` - serialized value may not be as expected [field_name='mode', input_value=3, input_type=int])
  return self.serializer.to_python(

INFO 03-08 10:21:46 [topk_topp_sampler.py:51] Using FlashInfer for top-p & top-k sampling.
INFO 03-08 10:21:46 [base.py:106] Offloader set to NoopOffloader
INFO 03-08 10:21:46 [gpu_model_runner.py:4255] Starting to load model unsloth/qwen2.5-3b-instruct-unsloth-bnb-4bit...
INFO 03-08 10:21:47 [cuda.py:405] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION'].
INFO 03-08 10:21:47 [flash_attn.py:587] Using FlashAttention version 2
INFO 03-08 10:21:47 [bitsandbytes_loader.py:786] Loading weights with BitsAndBytes quantization. May take a while ...

<frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
<frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.

model.safetensors:   0%|          | 0.00/2.36G [00:00<?, ?B/s]

INFO 03-08 10:21:52 [weight_utils.py:561] Time spent downloading weights for unsloth/qwen2.5-3b-instruct-unsloth-bnb-4bit: 4.193194 seconds
INFO 03-08 10:21:52 [weight_utils.py:601] No model.safetensors.index.json found in remote.

Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]

Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]

INFO 03-08 10:21:53 [punica_selector.py:20] Using PunicaWrapperGPU.
INFO 03-08 10:21:54 [gpu_model_runner.py:4338] Model loading took 2.26 GiB memory and 6.095089 seconds
INFO 03-08 10:22:03 [backends.py:916] Using cache directory: /root/.cache/vllm/torch_compile_cache/2dc9500b90/rank_0_0/backbone for vLLM's torch.compile
INFO 03-08 10:22:03 [backends.py:976] Dynamo bytecode transform time: 7.93 s

Unsloth: Compiling kernels: 100%|██████████| 3/3 [00:00<00:00,  8.60it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_3]

INFO 03-08 10:22:06 [backends.py:350] Cache the graph of compile range (1, 8192) for later use

Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 32.93it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 738.09it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 3/3 [00:00<00:00, 24.84it/s, triton_red_fused__to_copy_add_mean_mul_pow_rsqrt_2]

INFO 03-08 10:22:10 [backends.py:366] Compiling a graph for compile range (1, 8192) takes 5.91 s
INFO 03-08 10:22:10 [monitor.py:35] torch.compile takes 15.01 s in total
INFO 03-08 10:22:10 [decorators.py:580] saving AOT compiled function to /root/.cache/vllm/torch_compile_cache/torch_aot_compile/2ea6241b9f416a837277cee3f8dd81e1346836a3fa4a05c04962ce1a7b74aa0c/rank_0_0/model

INFO 03-08 10:22:12 [decorators.py:588] saved AOT compiled function to /root/.cache/vllm/torch_compile_cache/torch_aot_compile/2ea6241b9f416a837277cee3f8dd81e1346836a3fa4a05c04962ce1a7b74aa0c/rank_0_0/model
INFO 03-08 10:22:57 [gpu_worker.py:424] Available KV cache memory: 53.53 GiB
INFO 03-08 10:22:57 [kv_cache_utils.py:1314] GPU KV cache size: 1,559,024 tokens
INFO 03-08 10:22:57 [kv_cache_utils.py:1319] Maximum concurrency for 2,048 tokens per request: 761.24x

2026-03-08 10:22:57,399 - INFO - autotuner.py:256 - flashinfer.jit: [Autotuner]: Autotuning process starts ...
2026-03-08 10:22:57,474 - INFO - autotuner.py:262 - flashinfer.jit: [Autotuner]: Autotuning process ends

INFO 03-08 10:22:57 [vllm_utils.py:728] Unsloth: Running patched vLLM v1 `capture_model`.

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE):   0%|          | 0/70 [00:00<?, ?it/s]

WARNING 03-08 10:22:57 [utils.py:268] Using default LoRA kernel configs

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 70/70 [00:10<00:00,  6.79it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 38/38 [00:41<00:00,  1.09s/it]

INFO 03-08 10:23:49 [gpu_model_runner.py:5360] Graph capturing finished in 52 secs, took 0.08 GiB
INFO 03-08 10:23:49 [vllm_utils.py:735] Unsloth: Patched vLLM v1 graph capture finished in 52 secs.

INFO 03-08 10:23:50 [core.py:282] init engine (profile, create kv cache, warmup model) took 116.75 seconds
INFO 03-08 10:23:52 [llm.py:388] Supported tasks: ('generate',)
Unsloth: Just some info: will skip parsing ['q_norm', 'post_feedforward_layernorm', 'layer_norm1', 'pre_feedforward_layernorm', 'norm', 'ffn_norm', 'norm1', 'post_attention_layernorm', 'post_layernorm', 'norm2', 'attention_norm', 'input_layernorm', 'k_norm', 'layer_norm2']

Some weights of Qwen2ForCausalLM were not initialized from the model checkpoint at unsloth/qwen2.5-3b-instruct-unsloth-bnb-4bit and are newly initialized: ['lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Performing substitution for additional_keys=set()
Unsloth: Just some info: will skip parsing ['q_norm', 'post_feedforward_layernorm', 'layer_norm1', 'pre_feedforward_layernorm', 'norm', 'cross_attn_input_layernorm', 'ffn_norm', 'norm1', 'post_attention_layernorm', 'cross_attn_post_attention_layernorm', 'post_layernorm', 'norm2', 'attention_norm', 'input_layernorm', 'k_norm', 'layer_norm2']

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/605 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

unsloth/qwen2.5-3b-instruct-unsloth-bnb-4bit does not have a padding token! Will use pad_token = <|PAD_TOKEN|>.

Unsloth 2026.3.3 patched 36 layers with 36 QKV layers, 36 O layers and 36 MLP layers.

Model loaded: unsloth/Qwen2.5-3B-Instruct

In [5]:
# System prompt and task descriptions
SYSTEM_PROMPT = """\
You are a data-driven enterprise analyst. You answer questions about \
datasets across multiple domains (HR, Sales, Project Management, \
IT Operations) tailored to the audience persona.

Personas:
- Executive: Focus on costs, ROI, strategic risk, portfolio trends, year-over-year metrics.
- Manager: Focus on team performance, operational health, process bottlenecks, capacity.
- Individual Contributor: Focus on personal tasks, deadlines, what to do next.

Respond with a JSON answer:
{"answer": "<your answer>", "cited_columns": ["col1", "col2"], "reasoning": "<chain-of-thought>"}

Rules:
1. Ground every claim in the data.
2. Match your tone and vocabulary to the persona.
3. Be concise but thorough.
4. Never fabricate numbers."""

TASK_DESCRIPTIONS = [
    "Answer the question based on the data, tailored to the persona.",
    "Provide a data-grounded answer appropriate for this audience.",
    "Analyze the data and answer the question in the persona's style.",
    "Use the dataset to answer accurately, matching the persona's focus.",
    "Generate a faithful, persona-aligned answer citing real data.",
    "Answer using statistics from the data, in the right tone for this persona.",
    "Review the data summary and answer the question for this stakeholder.",
    "Craft a response grounded in the data that matches the persona's needs.",
]

In [6]:
# Dataset: pre-built with real environment observations
import random
from datasets import Dataset

random.seed(42)
SEEDS = [42 + i for i in range(64)]
prompts = []
persona_names = []

print("Building dataset with real environment observations...")
for i, seed in enumerate(SEEDS):
    task_desc = random.choice(TASK_DESCRIPTIONS)
    resp = requests.post(f"{ENV_URL}/web/reset", json={"seed": seed})
    resp.raise_for_status()
    obs = resp.json()["observation"]

    prompts.append([
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": (
            f"Domain: {obs['domain']}\nPersona: {obs['persona']}\n"
            f"Persona Focus: {obs['persona_description']}\n\n"
            f"Question: {obs['question']}\n\n"
            f"Dataset Summary:\n{obs['dataset_summary']}\n\n"
            f"Column Statistics:\n{obs['column_stats']}\n\n"
            f"Available Columns: {', '.join(obs['available_columns'])}\n\n"
            f"Task: {task_desc}"
        )},
    ])
    persona_names.append(obs["persona"])
    if (i + 1) % 16 == 0:
        print(f"  Built {i + 1}/64 examples")

dataset = Dataset.from_dict({
    "prompt": prompts,
    "seed": SEEDS,
    "persona_name": persona_names,
})
print(f"Dataset size: {len(dataset)}")

Building dataset with real environment observations...
  Built 16/64 examples
  Built 32/64 examples
  Built 48/64 examples
  Built 64/64 examples
Dataset size: 64

In [7]:
# Environment reward function (calls env directly with stored seeds)
def answering_env_reward(completions, **kwargs) -> list[float]:
    """Primary reward: replay env with stored seed, step with parsed action."""
    seeds = kwargs.get("seed", [0] * len(completions))
    rewards = []
    for completion, seed in zip(completions, seeds):
        try:
            text = _get_text(completion)
            action_dict = parse_answering_action(text)
            requests.post(f"{ENV_URL}/web/reset", json={"seed": int(seed)})
            resp = requests.post(f"{ENV_URL}/web/step", json={"action": action_dict})
            resp.raise_for_status()
            rewards.append(float(resp.json().get("reward", 0.0)))
        except Exception as e:
            print(f"Env error: {e}")
            rewards.append(0.0)
    return rewards

In [8]:
# GRPO training config
from trl import GRPOConfig

training_args = GRPOConfig(
    output_dir="./outputs/answering-grpo",
    use_vllm=True,
    learning_rate=LEARNING_RATE,
    adam_beta1=0.9,
    adam_beta2=0.99,
    weight_decay=0.1,
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    optim="adamw_8bit",
    num_train_epochs=NUM_TRAIN_EPOCHS,
    per_device_train_batch_size=PER_DEVICE_TRAIN_BATCH_SIZE,
    gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,
    num_generations=NUM_GENERATIONS,
    max_completion_length=MAX_COMPLETION_LENGTH,
    max_prompt_length=MAX_PROMPT_LENGTH,
    max_grad_norm=0.1,
    logging_steps=1, save_steps=50,
    report_to="wandb", run_name="datasage-answering-grpo-v2",
)
os.environ.setdefault("WANDB_PROJECT", WANDB_PROJECT)

Unsloth: We now expect `per_device_train_batch_size` * `gradient_accumulation_steps` * `world_size` to be a multiple of `num_generations`.
We will change the batch size of 1 to the `num_generations` of 8

'datasage'

In [9]:
# Create trainer and train
from trl import GRPOTrainer

trainer = GRPOTrainer(
    model=model, processing_class=tokenizer, args=training_args,
    train_dataset=dataset,
    reward_funcs=[answering_env_reward, patronus_reward_fn, answering_json_format_reward, persona_match_reward],
)
print("Starting Stage 3 (Answering) GRPO training...")
trainer.train()

Starting Stage 3 (Answering) GRPO training...

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 64 | Num Epochs = 3 | Total steps = 192
O^O/ \_/ \    Batch size per device = 8 | Gradient accumulation steps = 1
\        /    Data Parallel GPUs = 1 | Total batch size (8 x 1 x 1) = 8
 "-____-"     Trainable parameters = 29,933,568 of 3,115,872,256 (0.96% trained)
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from WANDB_API_KEY.
wandb: Currently logged in as: ricalanis to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

wandb: Detected [huggingface_hub.inference, openai] in use.
wandb: Use W&B Weave for improved LLM call tracing. Install Weave with `pip install weave` then add `import weave` to the top of your script.
wandb: For more information, check out the docs at: https://weave-docs.wandb.ai/

WARNING 03-08 10:24:19 [input_processor.py:168] vLLM has deprecated support for supporting different tokenizers for different LoRAs. By default, vLLM uses base model's tokenizer. If you are using a LoRA with its own tokenizer, consider specifying `--tokenizer [lora_path]` to use the LoRA tokenizer.
Unsloth: Will smartly offload gradients to save VRAM!
https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
Env error: 500 Server Error: Internal Server Error for url: https://ricalanis-datasage-answering.hf.space/web/step
Env error: 500 Server Error: Internal Server Error for url: https://ricalanis-datasage-answering.hf.space/web/step

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
Env error: 500 Server Error: Internal Server Error for url: https://ricalanis-datasage-answering.hf.space/web/step

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: : response content: {"results":[{"evaluator_id":"lynx-small-2024-07-23","profile_name":"patronus:hallucination","status":"validation_error","error_message":"More than 1 dict was extracted from LLM generation: '{\n    \"REASONING\": ['The QUESTION asks for an answer based on the data provided in the CONTEXT.', 'The CONTEXT lists the number of incidents and the mean SLATarget for various systems: Access, Network, Hardware, Email, and Software.', 'The ANSWER provides a detailed breakdown of the number of incidents and the mean SLATarget for each system, which is directly derived from the CONTEXT.', 'The ANSWER also includes a reasoning section that explains the methodology for identifying the most incident-prone systems, which aligns with the data provided in the CONTEXT.', 'The ANSWER is faithful to the CONTEXT because it accurately reflects the data given and provides a logical analysis based on that data.'],\n    \"HIGHLIGHTS\": ['{\"answer\": \"{\\\"most_incident_systems\\\": {'Access': {'count': 24, 'mean_SLATarget': 48.48}, 'Network': {'count': 24, 'mean_SLATarget': 48.62}, 'Hardware': {'count': 22, 'mean_SLATarget': 47.16}, 'Email': {'count': 16, 'mean_SLATarget': 47.97}, 'Software': {'count': 14, 'mean_SLATarget': 46.29}}}\", \"cited_columns\": [\"Category\", \"AffectedSystem\", \"SLATarget\"], \"reasoning\": \"The systems with the highest number of incidents based on the 'Category' field are 'Access', 'Network', 'Hardware', 'Email', and 'Software'. However, for a more comprehensive analysis, we should look at the mean SLATarget for each category because it can help us understand the performance in handling incidents related to those systems. The category with the highest mean SLATarget for each, combined with high impact and possibly frequent incidences across those categories, would likely be considered the most 'incriminating' systems by the\"],\n    \"SCORE\": PASS\n}'.","evaluation_result":null,"criteria":"patronus:hallucination"}]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 229, in _evaluate_one_process_resp
    raise UnrecoverableAPIError("", response=resp.response)
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: : response content: {"results":[{"evaluator_id":"lynx-small-2024-07-23","profile_name":"patronus:hallucination","status":"validation_error","error_message":"More than 1 dict was extracted from LLM generation: '{\n    \"REASONING\": ['The QUESTION asks for an answer based on the data provided in the CONTEXT.', 'The CONTEXT lists the number of incidents and the mean SLATarget for various systems: Access, Network, Hardware, Email, and Software.', 'The ANSWER provides a detailed breakdown of the number of incidents and the mean SLATarget for each system, which is directly derived from the CONTEXT.', 'The ANSWER also includes a reasoning section that explains the methodology for identifying the most incident-prone systems, which aligns with the data provided in the CONTEXT.', 'The ANSWER is faithful to the CONTEXT because it accurately reflects the data given and provides a logical analysis based on that data.'],\n    \"HIGHLIGHTS\": ['{\"answer\": \"{\\\"most_incident_systems\\\": {'Access': {'count': 24, 'mean_SLATarget': 48.48}, 'Network': {'count': 24, 'mean_SLATarget': 48.62}, 'Hardware': {'count': 22, 'mean_SLATarget': 47.16}, 'Email': {'count': 16, 'mean_SLATarget': 47.97}, 'Software': {'count': 14, 'mean_SLATarget': 46.29}}}\", \"cited_columns\": [\"Category\", \"AffectedSystem\", \"SLATarget\"], \"reasoning\": \"The systems with the highest number of incidents based on the 'Category' field are 'Access', 'Network', 'Hardware', 'Email', and 'Software'. However, for a more comprehensive analysis, we should look at the mean SLATarget for each category because it can help us understand the performance in handling incidents related to those systems. The category with the highest mean SLATarget for each, combined with high impact and possibly frequent incidences across those categories, would likely be considered the most 'incriminating' systems by the\"],\n    \"SCORE\": PASS\n}'.","evaluation_result":null,"criteria":"patronus:hallucination"}]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: : response content: {"results":[{"evaluator_id":"lynx-small-2024-07-23","profile_name":"patronus:hallucination","status":"validation_error","error_message":"More than 1 dict was extracted from LLM generation: '{\n    \"REASONING\": ['The QUESTION asks for an answer based on the data provided in the CONTEXT.', 'The CONTEXT lists the number of incidents and the mean SLATarget for various systems: Access, Network, Hardware, Email, and Software.', 'The ANSWER provides a detailed breakdown of the number of incidents and the mean SLATarget for each system, which is directly derived from the CONTEXT.', 'The ANSWER also includes a reasoning section that explains the methodology for identifying the most incident-prone systems, which aligns with the data provided in the CONTEXT.', 'The ANSWER is faithful to the CONTEXT because it accurately reflects the data given and provides a logical analysis based on that data.'],\n    \"HIGHLIGHTS\": ['{\"answer\": \"{\\\"most_incident_systems\\\": {'Access': {'count': 24, 'mean_SLATarget': 48.48}, 'Network': {'count': 24, 'mean_SLATarget': 48.62}, 'Hardware': {'count': 22, 'mean_SLATarget': 47.16}, 'Email': {'count': 16, 'mean_SLATarget': 47.97}, 'Software': {'count': 14, 'mean_SLATarget': 46.29}}}\", \"cited_columns\": [\"Category\", \"AffectedSystem\", \"SLATarget\"], \"reasoning\": \"The systems with the highest number of incidents based on the 'Category' field are 'Access', 'Network', 'Hardware', 'Email', and 'Software'. However, for a more comprehensive analysis, we should look at the mean SLATarget for each category because it can help us understand the performance in handling incidents related to those systems. The category with the highest mean SLATarget for each, combined with high impact and possibly frequent incidences across those categories, would likely be considered the most 'incriminating' systems by the\"],\n    \"SCORE\": PASS\n}'.","evaluation_result":null,"criteria":"patronus:hallucination"}]}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
Env error: 500 Server Error: Internal Server Error for url: https://ricalanis-datasage-answering.hf.space/web/step

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
Env error: 500 Server Error: Internal Server Error for url: https://ricalanis-datasage-answering.hf.space/web/step

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

Env error: 500 Server Error: Internal Server Error for url: https://ricalanis-datasage-answering.hf.space/web/step

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

Env error: 500 Server Error: Internal Server Error for url: https://ricalanis-datasage-answering.hf.space/web/step

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

Env error: 500 Server Error: Internal Server Error for url: https://ricalanis-datasage-answering.hf.space/web/step

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate
Env error: 500 Server Error: Internal Server Error for url: https://ricalanis-datasage-answering.hf.space/web/step
Env error: 500 Server Error: Internal Server Error for url: https://ricalanis-datasage-answering.hf.space/web/step

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

Env error: 500 Server Error: Internal Server Error for url: https://ricalanis-datasage-answering.hf.space/web/step

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluate
Env error: 500 Server Error: Internal Server Error for url: https://ricalanis-datasage-answering.hf.space/web/step

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

Env error: 500 Server Error: Internal Server Error for url: https://ricalanis-datasage-answering.hf.space/web/step

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

/tmp/ipykernel_5408/2897798421.py:180: UserWarning: The Patronus SDK has already been initialized. Duplicate initialization attempts are ignored.
  patronus.init()

https://api.patronus.ai/v1/evaluators
https://api.patronus.ai/v1/evaluator-criteria
https://api.patronus.ai/v1/evaluate

ERROR:patronus.sdk:Evaluator raised an exception: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 861, in _evaluate
    return self._get_api().evaluate_one_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 174, in evaluate_one_sync
    return self._evaluate_one_process_resp(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/api/api_client.py", line 218, in _evaluate_one_process_resp
    raise UnrecoverableAPIError(
patronus.api.api_client_base.UnrecoverableAPIError: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 537, in wrapper_sync
    ret = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/evals/evaluators.py", line 831, in evaluate
    resp = retry(
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/patronus/retry.py", line 75, in wrapper
    raise RetryError(attempts, max_attempts, e, traceback.format_exc())
patronus.api.api_client_base.RetryError: RetryError: execution failed after 1/3 attempts: UnrecoverableAPIError: Response with unexpected status code: 402: response content: {"detail":"Insufficient funds"}

TrainOutput(global_step=192, training_loss=0.029096953990422964, metrics={'train_runtime': 7240.4456, 'train_samples_per_second': 0.027, 'train_steps_per_second': 0.027, 'total_flos': 0.0, 'train_loss': 0.029096953990422964})

In [10]:
# Save and push to Hub
output_dir = "./outputs/answering-grpo-final"
trainer.save_model(output_dir)
tokenizer.save_pretrained(output_dir)
print(f"Model saved to {output_dir}")

print(f"Pushing to Hub: {HF_REPO}")
trainer.push_to_hub(HF_REPO)
print(f"Model pushed to https://huggingface.co/{HF_REPO}")

Model saved to ./outputs/answering-grpo-final
Pushing to Hub: ricalanis/datasage-qwen-answering

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...adapter_model.safetensors:   0%|          |  554kB /  120MB

  ...ering-grpo/tokenizer.json:  30%|###       | 3.46MB / 11.4MB

  ...ng-grpo/training_args.bin:   1%|          |  73.0B / 7.38kB

Model pushed to https://huggingface.co/ricalanis/datasage-qwen-answering